# Generated by Django 3.1.5 on 2021-01-19 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles_subd', '0002_auto_20210119_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название статьи')),
                ('english_form_name', models.CharField(blank=True, max_length=250, verbose_name='name')),
                ('year', models.IntegerField(verbose_name='Год издания')),
                ('page', models.CharField(blank=True, max_length=250, verbose_name='страницы')),
                ('volume', models.IntegerField(blank=True, max_length=250, verbose_name='номер')),
                ('grant_ref', models.CharField(blank=True, max_length=250, verbose_name='ссылки на грант')),
                ('abstract', models.TextField(blank=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articles_subd.journal')),
            ],
        ),
    ]
