# Generated by Django 3.1.5 on 2021-01-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles_subd', '0003_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='volume',
            field=models.IntegerField(blank=True, verbose_name='номер'),
        ),
    ]
