# Generated by Django 3.1.5 on 2021-01-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles_subd', '0004_auto_20210119_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(to='articles_subd.Author'),
        ),
    ]
