# Generated by Django 3.1.5 on 2021-01-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles_subd', '0005_article_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pdf_file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='volume',
            field=models.IntegerField(blank=True, null=True, verbose_name='номер'),
        ),
    ]
